dotfiles_set_bashrc: false
dotfiles_gnome_extensions: false
dotfiles_opinionated_apps: false
dotfiles_install_kubernetes_clients: false
dotfiles_displaylink_compatibility: false
dotfiles_install_and_configure_docker: false
dotfiles_terminal_and_global_shortcuts: false
dotfiles_install_nvm_node: false
dotfiles_pdf_tools_xournalpp: false
dotfiles_install_nextcloud_desktop: false
dotfiles_logiops_driver: false
dotfiles_skip_logiops_driver_compilation: false
