---
argument_specs:
    main:
        options:
            # switches
            dotfiles_set_bashrc:
                type: bool
                required: false
            dotfiles_displaylink_compatibility:
                type: bool
                required: false
            dotfiles_gnome_extensions:
                type: bool
                required: false
            dotfiles_install_kubernetes_clients:
                type: bool
                required: false
            dotfiles_opinionated_apps:
                type: bool
                required: false
            dotfiles_install_and_configure_docker:
                type: bool
                required: false
            dotfiles_terminal_and_global_shortcuts:
                type: bool
                required: false
            dotfiles_install_nvm_node:
                type: bool
                required: false
            dotfiles_pdf_tools_xournalpp:
                type: bool
                required: false
            dotfiles_install_nextcloud_desktop:
                type: bool
                required: false
            dotfiles_logiops_driver:
                type: bool
                required: false
            dotfiles_skip_logiops_driver_compilation:
                type: bool
                required: false
            dotfiles_ckb_keyboard_driver:
                type: bool
                required: false
            # configs:
            dotfiles_profile_name:
                type: str
                required: true
            dotfiles_device_type:
                type: str
                choices:
                    - desktop
                    - laptop
                required: true
