---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: pihole-values
    namespace: pihole
    files:
      - values.yaml=values.yaml
    options:
      labels:
        reconcile.fluxcd.io/watch: "Enabled"
patches:
  - path: release.yaml
    target:
      kind: HelmRelease
      name: pihole
configurations:
  - kustomizeconfig.yaml
resources:
  - namespace.yaml
  - source.yaml
  - chart.yaml
  - release.yaml
  - service.yaml
  - httproute.yaml
