# https://artifacthub.io/packages/helm/mojo2600/pihole
---
persistentVolumeClaim:
  enabled: true

serviceWeb:
  enabled: false # We create the service manually - deactivation did not work though.... it is named `pihole-web`
  https:
    enabled: false

serviceDns:
  enabled: true
  nodePort: 30053
  mixedService: true

serviceDhcp:
  enabled: false

admin:
  existingSecret: pihole-admin-pw
  passwordKey: password
