# https://artifacthub.io/packages/helm/mojo2600/pihole
---
persistentVolumeClaim:
  enabled: true

serviceWeb:
  enabled: true
  https:
    enabled: false

serviceDns:
  enabled: true

serviceDhcp:
  enabled: false

admin:
  existingSecret: pihole-admin-pw
  passwordKey: password
