---
argument_specs:
    main:
        options:
            nginx_stream_ha_stream_enabled:
                type: bool
                required: false
            nginx_stream_ha_https_enabled:
                type: bool
                required: false
            nginx_stream_cloud_https_enabled:
                type: bool
                required: false
            nginx_stream_default_https_enabled:
                type: bool
                required: false
            nginx_stream_place_ssl_certs:
                type: bool
                required: false
            nginx_stream_certs_path:
                type: str
                required: false
            nginx_stream_default_server_name:
                type: str
                required: false
            nginx_stream_cloud_domain:
                type: str
                required: false
            nginx_stream_ha_domain:
                type: str
                required: false
            nginx_stream_ha_port:
                type: int
                required: false
            nginx_stream_into_k3s:
                type: list
                required: false
                elements: dict
                options:
                    port_from:
                        type: int
                        required: true
                    port_to:
                        type: int
                        required: true
                    tcp:
                        type: bool
                        required: true
                    udp:
                        type: bool
                        required: true
                    target_ip:
                        type: str
                        required: true
