---
argument_specs:
    main:
        options:
            unifi_firewall_writing_unifi_token:
                type: str
                required: true
                description: "Generate: https://unifi.ui.com/ > Network > Settings > Control Plane > Integrations"
            unifi_firewall_writing_console_ip:
                type: str
                required: false
                description: "Your console IP (LAN)"
            unifi_firewall_writing_print_debug:
                type: bool
                required: false
            unifi_firewall_writing_replacement_dict:
                type: list
                elements: dict
                options:
                    name:
                        type: str
                        required: true
                    replacement_ip:
                        type: str
                        required: true
                required: false
