# gimp
# chrome
# inkscape
# signal-desktop
# spotify
# simple screen recorder
# vlc
# vscode
# thunderbird
# discord
# audacity
# curl, wget
# texlive-full
# kdenlive
# minecraft-launcher
# ncat
# rpi-imager
# wireshark
# localsend
# firefox
