---
# https://launchpad.net/~tatokis/+archive/ubuntu/ckb-next
- name: Ensure software-properties-common is installed
  ansible.builtin.package:
      name: software-properties-common
      state: present
      update_cache: true
      cache_valid_time: 1800

- name: Add ckb-next PPA
  ansible.builtin.apt_repository:
      repo: ppa:tatokis/ckb-next
      state: present
      update_cache: true

# https://github.com/ckb-next/ckb-next
- name: Install System level ckb-next package
  ansible.builtin.package:
      name:
          - ckb-next
      state: present
      update_cache: true
      cache_valid_time: 1800

- name: Ensure ckb config directory exists
  ansible.builtin.file:
      path: ~/.config/ckb-next/
      state: directory
      # owner: "{{ dotfiles_profile_name }}"
      # group: "{{ dotfiles_profile_name }}"
      mode: "0755"
  become: false

- name: Place `ckb-next.conf` config file
  ansible.builtin.template:
      src: .bash_logout.j2
      dest: "~/.config/ckb-next/ckb-next.conf"
      mode: "664"
  become: false

- name: Reload ckb-next-daemon
  ansible.builtin.service:
      name: ckb-next-daemon
      state: restarted
