---
# with docker compose -> the role does it
# https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/docker/documentation/
- name: Install docker and services locally
  ansible.builtin.include_role:
      name: geerlingguy.docker
# ---

# Probably necessary to avoid apt warnings:
# sudo nano /etc/apt/sources.list.d/docker.sources
# add (as last line):        Architectures: amd64
