---
- name: Install kubectl locally
  ansible.builtin.include_role:
      name: andrewrothstein.kubectl

- name: Generate kubectl completion script
  ansible.builtin.command: kubectl completion bash
  register: dotfiles_kubectl_completion
  changed_when: false

- name: Write kubectl completion to system directory
  ansible.builtin.copy:
      content: "{{ dotfiles_kubectl_completion.stdout }}"
      dest: /etc/bash_completion.d/kubectl
      owner: root
      group: root
      mode: "0644"

- name: Install helm locally
  ansible.builtin.include_role:
      name: geerlingguy.helm

- name: Generate helm completion script
  ansible.builtin.command: helm completion bash
  register: dotfiles_helm_completion
  changed_when: false

- name: Write helm completion to system directory
  ansible.builtin.copy:
      content: "{{ dotfiles_helm_completion.stdout }}"
      dest: /etc/bash_completion.d/helm
      owner: root
      group: root
      mode: "0644"

- name: Install kubectl oidc-login plugin via krew
  ansible.builtin.command: kubectl krew install oidc-login
  args:
      creates: "~/.krew/store/oidc-login"
  become: false

- name: Place kubectl `config` file in invoking user's home directory
  ansible.builtin.copy:
      src: "{{ playbook_dir }}/../secrets/kubectl_config"
      dest: "~/.kube/config"
      mode: "0600"
      backup: true
  become: false

- name: Download Flux install script
  ansible.builtin.get_url:
      url: https://fluxcd.io/install.sh
      dest: /tmp/flux_install.sh
      mode: "0755"

- name: Execute Flux install script
  ansible.builtin.command: /tmp/flux_install.sh
  args:
      creates: /usr/local/bin/flux

- name: Remove Flux install script
  ansible.builtin.file:
      path: /tmp/flux_install.sh
      state: absent

- name: Generate flux completion script
  ansible.builtin.command: flux completion bash
  register: dotfiles_flux_completion
  changed_when: false

- name: Write flux completion to system directory
  ansible.builtin.copy:
      content: "{{ dotfiles_flux_completion.stdout }}"
      dest: /etc/bash_completion.d/flux
      owner: root
      group: root
      mode: "0644"

- name: Install k9s locally
  ansible.builtin.include_role:
      name: andrewrothstein.k9s
