- name: Place Bashrc include
  when: dotfiles_set_bashrc
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/bashrc.yml"

- name: Install Kubernetes Dependencies
  when: dotfiles_install_kubernetes_clients
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/kubernetes.yml"

- name: Update Gnome (Shell) Extensions
  when: dotfiles_gnome_extensions
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/gnome_exts.yml"

- name: Install opinionated programs/apps
  when: dotfiles_opinionated_apps
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/apps.yml"

- name: Install Displaylink compatibility
  when: dotfiles_displaylink_compatibility
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/display_link.yml"
# ---

# --- Where stuff could be looked up from (opinionated configs by friends)
# https://github.com/jan-clr/dotfiles
# https://gitlab.com/FStrk/dotfiles
