---
- name: Place Bashrc include
  when: dotfiles_set_bashrc
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/bashrc.yml"

- name: Install Kubernetes Dependencies
  when: dotfiles_install_kubernetes_clients
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/kubernetes.yml"

- name: Update Gnome (Shell) Extensions
  when: dotfiles_gnome_extensions
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/gnome_exts.yml"

- name: Install opinionated programs/apps
  when: dotfiles_opinionated_apps
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/apps.yml"

- name: Install Displaylink compatibility
  when: dotfiles_displaylink_compatibility
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/display_link.yml"

- name: Install Docker and deamons
  when: dotfiles_install_and_configure_docker
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/docker.yml"

- name: Install Terminal and set global shortcuts
  when: dotfiles_terminal_and_global_shortcuts
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/terminator.yml"

- name: Install NVM
  when: dotfiles_install_nvm_node
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/nvm.yml"

- name: PDF tools and Xournalpp
  when: dotfiles_pdf_tools_xournalpp
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/xournalpp.yml"

- name: Nextcloud Desktop
  when: dotfiles_install_nextcloud_desktop
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/nextcloud.yml"

- name: Logiops Driver
  when: dotfiles_logiops_driver
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/mx_master.yml"

- name: CKB Next Driver
  when: dotfiles_ckb_keyboard_driver
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/ckb.yml"

- name: Drive offline sync
  when: dotfiles_drive_offline_sync
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/drive.yml"
# ---

# --- Where stuff could be looked up from (opinionated configs by friends)
# https://github.com/jan-clr/dotfiles
# https://gitlab.com/FStrk/dotfiles
