---
# https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

- name: Add deadsnakes PPA
  ansible.builtin.apt_repository:
      repo: ppa:deadsnakes/ppa
      state: present
      update_cache: true
# sudo add-apt-repository ppa:deadsnakes/ppa -y # no warnings
# TODO convert to use apt-key (like e.g. vscode)
