---
# Important: Disable "Cosmic Dock" (= modified version of "dash-to-dock")

- name: Install CLI tool to manage GNOME extensions
  ansible.builtin.pip:
      name: gnome-extensions-cli
      extra_args: --user --upgrade

- name: Install and enable GNOME extensions
  ansible.builtin.command:
      cmd: gext install "gTile@vibou" gext enable "gTile@vibou"
# ---

# sudo apt install gnome-tweaks
# sudo apt install gnome-shell-extensions

# dash-to-panel@jderose9.github.com
# ding@rastersoft.com
# Vitals@CoreCoding.com
# sound-output-device-chooser@kgshank.net
# extension-list@tu.berry
# gnome-shell-screenshot@ttll.de
# nvidiautil@ethanwharris
# popx11gestures@system76.com
# cosmic-workspaces@system76.com
# pop-cosmic@system76.com
# pop-shell@system76.com
# system76-power@system76.com
# ubuntu-appindicators@ubuntu.com

# flatpak install --user com.discordapp.Discord -y
# flatpak install --user com.geeks3d.furmark -y
# flatpak install --user com.github.arminstraub.krop -y
# flatpak install --user com.github.hluk.copyq -y
# flatpak install --user com.slack.Slack -y
# flatpak install --user com.spotify.Client -y
# flatpak install --user io.github.vikdevelop.SaveDesktop -y
# flatpak install --user org.gimp.GIMP -y
# flatpak install --user org.gnome.GHex -y
# flatpak install --user org.mozilla.Thunderbird -y
# flatpak install --user org.torproject.torbrowser-launcher -y
# flatpak install --user org.videolan.VLC -y
