---
- name: Install nginx and stream module
  ansible.builtin.package:
      name:
          - nginx
          - libnginx-mod-stream
      state: present
      update_cache: true

- name: Ansible controlled nginx.conf
  ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx

- name: Ensure stream config directory exists
  ansible.builtin.file:
      path: /etc/nginx/stream-conf.d
      state: directory
      owner: root
      group: root
      mode: "0755"

- name: Deploy HomeAssistant stream config
  ansible.builtin.template:
      src: stream-homeassistant.conf.j2
      dest: /etc/nginx/stream-conf.d/homeassistant.conf
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx
