---
- name: Install nginx and stream module
  ansible.builtin.package:
      name:
          - nginx
          - libnginx-mod-stream
      state: present
      update_cache: true
      cache_valid_time: 1800

- name: Ansible controlled nginx.conf
  ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx

- name: Remove default Nginx site
  ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  notify: Reload nginx

# Stream configs

- name: Ensure stream config directory exists
  ansible.builtin.file:
      path: /etc/nginx/stream-conf-available.d
      state: directory
      owner: root
      group: root
      mode: "0755"

- name: Ensure stream config enabled directory exists
  ansible.builtin.file:
      path: /etc/nginx/stream-conf-enabled.d
      state: directory
      owner: root
      group: root
      mode: "0755"

- name: Deploy HomeAssistant stream config
  ansible.builtin.template:
      src: stream-homeassistant.conf.j2
      dest: /etc/nginx/stream-conf-available.d/homeassistant.conf
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx

- name: Enable HomeAssistant stream config
  ansible.builtin.file:
      src: /etc/nginx/stream-conf-available.d/homeassistant.conf
      dest: /etc/nginx/stream-conf-enabled.d/homeassistant.conf
      state: link
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx

# Http(s) configs

- name: Deploy Https Default config
  ansible.builtin.template:
      src: default.conf.j2
      dest: /etc/nginx/sites-available/zzzz-default-ssl-proxy.conf
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx

- name: Enable Https Default config
  ansible.builtin.file:
      src: /etc/nginx/sites-available/zzzz-default-ssl-proxy.conf
      dest: /etc/nginx/sites-enabled/zzzz-default-ssl-proxy.conf
      state: link
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx

- name: Deploy Https Cloud Proxy config
  ansible.builtin.template:
      src: proxy-cloud.conf.j2
      dest: /etc/nginx/sites-available/cloud-ssl-proxy.conf
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx

- name: Enable Https Cloud Proxy config
  ansible.builtin.file:
      src: /etc/nginx/sites-available/cloud-ssl-proxy.conf
      dest: /etc/nginx/sites-enabled/cloud-ssl-proxy.conf
      state: link
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx

- name: Deploy Https HA Proxy config
  ansible.builtin.template:
      src: proxy-ha.conf.j2
      dest: /etc/nginx/sites-available/ha-ssl-proxy.conf
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx

- name: Enable Https HA Proxy config
  ansible.builtin.file:
      src: /etc/nginx/sites-available/ha-ssl-proxy.conf
      dest: /etc/nginx/sites-enabled/ha-ssl-proxy.conf
      state: link
      owner: root
      group: root
      mode: "0644"
  notify: Reload nginx

# SSL certs

- name: Place SSL certs
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/place_ssl_certs.yml"
  vars:
      ssl_cert_src_dir: "{{ playbook_dir }}/../secrets"
      ssl_cert_dest_dir: /etc/ionoshttps/kellehorreur.de/
      ssl_cert_files:
          - name: privkey.pem
            mode: "0600"
          - name: fullchain.pem
            mode: "0644"

- name: Trigger reload if certs changed
  ansible.builtin.command: /bin/true
  changed_when: nginx_stream_ssl_cert_copy is changed
  notify: Reload nginx
