firewall_allow_ipv6_ssh: false
firewall_allow_http: none
firewall_allow_https: none
firewall_allow_ha: none
firewall_allow_k3s: none
firewall_allow_dns: false
firewall_ha_port: 8123
firewall_k3s_port: 6443
