---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - demo-kustomization.yaml # deactivated, as no http only route needed for testing anymore
  - smbstorage.yaml
  - pihole-kustomization.yaml
  - nextcloud-kustomization.yaml
