---
- name: Install ufw
  ansible.builtin.package:
      name:
          - ufw
      state: present
      update_cache: true
      cache_valid_time: 1800

# Reset and SSH

- name: Reset UFW
  community.general.ufw:
      state: reset

- name: Reject IPv6 SSH (tcp/22) # SSH first so we do not loose access - but block before accept
  when: not firewall_allow_ipv6_ssh
  community.general.ufw:
      comment: SSH override
      rule: reject
      direction: in
      port: "22"
      to_ip: "::/0"

- name: Allow SSH (tcp/22) # SSH first so we do not loose access
  community.general.ufw:
      comment: SSH
      rule: allow
      proto: tcp
      port: "22"

- name: Enable UFW with default reject policy
  community.general.ufw:
      state: enabled
      policy: reject

#### How this works
#### First rule that matches is taken
#### the idempotence of this is not reliable -> we need to call "state: reset" and then re-add all rules to ensure order and no rules being lef over
#### because it tries to produce per-rule idempotence, having a deny rule for "to_ip, proto, to_port" and later a accept rule does not work
#### port + proto is used to match rules and they will get overwritten
#### Also adding rules ALWAYS adds them vor ipv4 AND ipv6 (can not be avoided)
#### solution: block rules block udp + tcp, while the allow rules only allow the respective proto
#### as the default is reject, this is still logically correct

# Http

- name: Reject HTTP (tcp/80) on IPv4
  when: firewall_allow_http in ["ipv6"]
  community.general.ufw:
      comment: Http override
      rule: reject
      direction: in
      port: "80"
      to_ip: "0.0.0.0/0"

- name: Reject HTTP (tcp/80) on IPv6
  when: firewall_allow_http in ["ipv4"]
  community.general.ufw:
      comment: Http override
      rule: reject
      direction: in
      port: "80"
      to_ip: "::/0"

- name: Allow HTTP (tcp/80)
  when: firewall_allow_http in ["ipv4", "ipv6", "both"]
  community.general.ufw:
      comment: Http
      rule: allow
      proto: tcp
      port: "80"

# Https

- name: Reject HTTPS (tcp/443) on IPv4
  when: firewall_allow_https in ["ipv6"]
  community.general.ufw:
      comment: Https override
      rule: reject
      direction: in
      port: "443"
      to_ip: "0.0.0.0/0"

- name: Reject HTTPS (tcp/443) on IPv6
  when: firewall_allow_https in ["ipv4"]
  community.general.ufw:
      comment: Https override
      rule: reject
      direction: in
      port: "443"
      to_ip: "::/0"

- name: Allow HTTPS (tcp/443)
  when: firewall_allow_https in ["ipv4", "ipv6", "both"]
  community.general.ufw:
      comment: Https
      rule: allow
      proto: tcp
      port: "443"

# DNS

- name: Reject DNS (tcp + udp/53) on IPv4
  when: firewall_allow_dns in ["ipv6"]
  community.general.ufw:
      comment: DNS override
      rule: reject
      direction: in
      port: "53"
      to_ip: "0.0.0.0/0"

- name: Reject DNS (tcp + udp/53) on IPv6
  when: firewall_allow_dns in ["ipv4"]
  community.general.ufw:
      comment: DNS override
      rule: reject
      direction: in
      port: "53"
      to_ip: "::/0"

- name: Allow DNS (tcp + udp/53)
  when: firewall_allow_dns in ["ipv4", "ipv6", "both"]
  community.general.ufw:
      comment: DNS
      rule: allow
      proto: tcp
      port: "53"

- name: Allow DNS (tcp + udp/53)
  when: firewall_allow_dns in ["all_but_global_unicast"]
  community.general.ufw:
      comment: DNS
      rule: allow
      proto: tcp
      from_ip: "0.0.0.0/0"
      port: "53"

- name: Allow DNS (tcp + udp/53)
  when: firewall_allow_dns in ["all_but_global_unicast"]
  community.general.ufw:
      comment: DNS
      rule: allow
      proto: tcp
      from_ip: "fc00::/7" # specifically allow unique local traffic
      port: "53"

- name: Allow DNS (tcp + udp/53)
  when: firewall_allow_dns in ["ipv4", "ipv6", "both"]
  community.general.ufw:
      comment: DNS
      rule: allow
      proto: udp
      port: "53"

- name: Allow DNS (tcp + udp/53)
  when: firewall_allow_dns in ["all_but_global_unicast"]
  community.general.ufw:
      comment: DNS
      rule: allow
      proto: udp
      from_ip: "0.0.0.0/0"
      port: "53"

- name: Allow DNS (tcp + udp/53)
  when: firewall_allow_dns in ["all_but_global_unicast"]
  community.general.ufw:
      comment: DNS
      rule: allow
      proto: udp
      from_ip: "fc00::/7" # specifically allow unique local traffic
      port: "53"

# Home Assistant

- name: Reject tcp port for HomeAssistant
  when: firewall_allow_ha in ["ipv6"]
  community.general.ufw:
      comment: HomeAssistant override
      rule: reject
      direction: in
      port: "{{ firewall_ha_port | default('8123') }}"
      to_ip: "0.0.0.0/0"

- name: Reject tcp port for HomeAssistant
  when: firewall_allow_ha in ["ipv4"]
  community.general.ufw:
      comment: HomeAssistant override
      rule: reject
      direction: in
      port: "{{ firewall_ha_port | default('8123') }}"
      to_ip: "::/0"

- name: Allow tcp port for HomeAssistant
  when: firewall_allow_ha in ["ipv4", "ipv6", "both"]
  community.general.ufw:
      comment: HomeAssistant
      rule: allow
      proto: tcp
      port: "{{ firewall_ha_port | default('8123') }}"

# Turn

- name: Reject tcp AND udp port for Turn
  when: firewall_allow_turn in ["ipv6"]
  community.general.ufw:
      comment: Turn override
      rule: reject
      direction: in
      port: "{{ firewall_turn_port | default('3478') }}"
      to_ip: "0.0.0.0/0"

- name: Reject tcp AND udp port for Turn
  when: firewall_allow_turn in ["ipv4"]
  community.general.ufw:
      comment: Turn override
      rule: reject
      direction: in
      port: "{{ firewall_turn_port | default('3478') }}"
      to_ip: "::/0"

- name: Allow tcp port for Turn
  when: firewall_allow_turn in ["ipv4", "ipv6", "both"]
  community.general.ufw:
      comment: Turn
      rule: allow
      proto: tcp
      port: "{{ firewall_turn_port | default('3478') }}"

- name: Allow udp port for Turn
  when: firewall_allow_turn in ["ipv4", "ipv6", "both"]
  community.general.ufw:
      comment: Turn
      rule: allow
      proto: udp
      port: "{{ firewall_turn_port | default('3478') }}"

# Kubernetes

- name: Reject tcp port for k8s/k3s apiserver
  when: firewall_allow_k3s in ["ipv6"]
  community.general.ufw:
      comment: "k8s/k3s apiserver override"
      rule: reject
      direction: in
      port: "{{ firewall_k3s_port | default('6443') }}"
      to_ip: "0.0.0.0/0"

- name: Reject tcp port for k8s/k3s apiserver
  when: firewall_allow_k3s in ["ipv4"]
  community.general.ufw:
      comment: "k8s/k3s apiserver override"
      rule: reject
      direction: in
      port: "{{ firewall_k3s_port | default('6443') }}"
      to_ip: "::/0"

- name: Allow tcp port for k8s/k3s apiserver
  when: firewall_allow_k3s in ["ipv4", "ipv6", "both"]
  community.general.ufw:
      comment: "k8s/k3s apiserver"
      rule: allow
      proto: tcp
      port: "{{ firewall_k3s_port | default('6443') }}"

- name: Allow pod network (10.42.0.0/16)
  when: not (firewall_allow_k3s == "none")
  community.general.ufw:
      rule: allow
      src: 10.42.0.0/16
      comment: "k8s/k3s pods"

- name: Allow service network (10.43.0.0/16)
  when: not (firewall_allow_k3s == "none")
  community.general.ufw:
      rule: allow
      src: 10.43.0.0/16
      comment: "k8s/k3s services"

# Finally: reload

- name: Reload the UFW
  community.general.ufw:
      state: reloaded
