---
argument_specs:
    main:
        options:
            firewall_allow_http:
                type: bool
                required: false
            firewall_allow_https:
                type: bool
                required: false
            firewall_allow_ha:
                type: bool
                required: false
            firewall_ha_port:
                type: int
                required: false
