---
argument_specs:
    main:
        options:
            firewall_allow_ipv6_ssh:
                type: bool
                required: false
            firewall_allow_http:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_allow_https:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_allow_turn:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_allow_ha:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_allow_ha_2:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_allow_k3s:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_allow_dns:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
                    - all_but_global_unicast
            firewall_ha_port:
                type: int
                required: false
            firewall_ha_2_port:
                type: int
                required: false
            firewall_k3s_port:
                type: int
                required: false
            firewall_turn_port:
                type: int
                required: false
