---
argument_specs:
    main:
        options:
            firewall_allow_ipv6_ssh:
                type: bool
                required: false
            firewall_allow_http:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_allow_https:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_allow_ha:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_allow_k3s:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_allow_dns:
                type: str
                required: false
                choices:
                    - ipv4
                    - ipv6
                    - both
                    - none
            firewall_ha_port:
                type: int
                required: false
            firewall_k3s_port:
                type: int
                required: false
