---
argument_specs:
    main:
        options:
            k8s_tls_namespace:
                type: str
                required: false
            k8s_tls_secret_name:
                type: str
                required: true
