---
- name: Validate Unifi interaction vars
  ansible.builtin.assert:
      that:
          - unifi_firewall_writing_unifi_token is defined
      fail_msg: >
          Required variables:
          unifi_firewall_writing_unifi_token

- name: Get site info
  ubiquiti.unifi_api.network:
      path: "/v1/sites"
      method: GET
      base_url: "{{ unifi_firewall_writing_base_url }}"
      token: "{{ unifi_firewall_writing_unifi_token }}"
  register: unifi_firewall_writing_site_info

- name: Print site info
  when: unifi_firewall_writing_print_debug
  ansible.builtin.debug:
      var: unifi_firewall_writing_site_info.data

- name: Extract the id with json_query
  ansible.builtin.set_fact:
      unifi_firewall_writing_site_id: >-
          {{ unifi_firewall_writing_site_info.data |
          community.general.json_query('data[?internalReference==`default`].id') |
          first }}

- name: Print site id
  when: unifi_firewall_writing_print_debug
  ansible.builtin.debug:
      var: unifi_firewall_writing_site_id

- name: Get ip-list-info
  ubiquiti.unifi_api.network:
      path: "/v1/sites/{{ unifi_firewall_writing_site_id }}/traffic-matching-lists"
      method: GET
      base_url: "{{ unifi_firewall_writing_base_url }}"
      token: "{{ unifi_firewall_writing_unifi_token }}"
  register: unifi_firewall_writing_ip_list_info

- name: Print ip-list-info
  when: unifi_firewall_writing_print_debug
  ansible.builtin.debug:
      var: unifi_firewall_writing_ip_list_info.data

- name: Query data from result and match to input
  ansible.builtin.set_fact:
      unifi_firewall_writing_firewall_tasks: >-
          {{
            unifi_firewall_writing_firewall_tasks | default([])
            + [
                item | combine({
                  'id': (
                    unifi_firewall_writing_ip_list_info.data.data
                    | selectattr('name', 'equalto', item.name)
                    | map(attribute='id')
                    | first
                  ),
                  'current': (
                    (
                      unifi_firewall_writing_ip_list_info.data.data
                      | selectattr('name', 'equalto', item.name)
                      | map(attribute='items')
                      | first
                      | map(attribute='value')
                      | first
                    )
                  ),
                  'different': (
                    (
                      unifi_firewall_writing_ip_list_info.data.data
                      | selectattr('name', 'equalto', item.name)
                      | map(attribute='items')
                      | first
                      | map(attribute='value')
                      | first
                    )
                    !=
                    (
                      item.replacement_ip
                    )
                  )
                })
              ]
          }}
  loop: "{{ unifi_firewall_writing_replacement_dict }}"
  loop_control:
      loop_var: item

- name: Print update task list
  when: unifi_firewall_writing_print_debug
  ansible.builtin.debug:
      var: unifi_firewall_writing_firewall_tasks

# ! This is not properly idempotent (because unifi did not implement this properly)! Not sure if this changed!
- name: Update Traffic Matching List
  ubiquiti.unifi_api.network:
      base_url: "{{ unifi_firewall_writing_base_url }}"
      token: "{{ unifi_firewall_writing_unifi_token }}"
      path: "/v1/sites/{{ unifi_firewall_writing_site_id }}/traffic-matching-lists/{{ item.id }}"
      method: PUT
      body:
          type: "IPV6_ADDRESSES"
          name: "{{ item.name }}"
          items:
              - type: IP_ADDRESS
                value: "{{ item.replacement_ip }}"
  loop: "{{ unifi_firewall_writing_firewall_tasks }}"
  loop_control:
      loop_var: item
  when: item.different | bool
# ---
# Lists can be found at: https://unifi.ui.com/ > Network > Settings > Overview > Network Lists

# https://developer.ui.com/network/v10.0.162/updatetrafficmatchinglist
