---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      # the WHOLE chart (including valuesFiles key could be inlined here) https://fluxcd.io/flux/components/source/helmcharts/#values-files
      chartRef:
        kind: HelmChart
        name: traefik

# list current listeners               kubectl get gateways.gateway.networking.k8s.io -n flux-system traefik-gateway -o yaml
