# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md
---
providers: # enable Gateway API provider nothing else
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway: # https://gateway-api.sigs.k8s.io/reference/1.4/spec/#gateway
  # defaultScope: "All" # currently experimental setting
  listeners: # https://gateway-api.sigs.k8s.io/reference/1.4/spec/#listener
    web:
      port: 80
      hostname: ""
      protocol: HTTP
      namespacePolicy:
        from: All

    websecure:
      port: 443
      protocol: HTTPS
      namespacePolicy:
        from: All
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: tls-certificate

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 30080 # no rights to expose 80 directly as that is a priviledged port

  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 30443 # == nodePort of a Service


# expose without a cluster load balancer (not HA compatible) -> Add a standalone load balancer sometime maybe
# Needs config: but that runs traefik as root
# https://github.com/traefik/traefik-helm-chart/issues/336#issuecomment-776163841

# This automatically installs a default GatewayClass and default Gateway. This could be overwritten, see https://github.com/marcel-dempers/docker-development-youtube-series/blob/master/kubernetes/gateway-api/values.yaml
