# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/
# https://github.com/traefik/traefik-helm-chart/blob/master/traefik/VALUES.md
---
providers: # enable Gateway API provider nothing else
  kubernetesCRD:
    enabled: false
  kubernetesIngress:
    enabled: false
  kubernetesGateway:
    enabled: true

gateway: # https://gateway-api.sigs.k8s.io/reference/1.4/spec/#gateway
  # defaultScope: "All" # currently experimental setting
  listeners: # https://gateway-api.sigs.k8s.io/reference/1.4/spec/#listener
    web:
      port: 80
      hostname: ""
      protocol: HTTP
      namespacePolicy:
        from: All

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80

# expose without a cluster load balancer (not HA compatible) -> Add a standalone load balancer sometime maybe
hostNetwork: true
securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE

# This automatically installs a default GatewayClass and default Gateway. This could be overwritten, see https://github.com/marcel-dempers/docker-development-youtube-series/blob/master/kubernetes/gateway-api/values.yaml
