---
# https://artifacthub.io/packages/helm/nextcloud/nextcloud
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m0s
  reconcileStrategy: ChartVersion
  chart: nextcloud
  sourceRef:
    kind: HelmRepository
    name: nextcloud
  version: 8.8.1
