---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data-claim
  namespace: nextcloud
spec:
  storageClassName: smb-csi
  volumeName: nextcloud-data
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
