# https://github.com/nextcloud/helm/tree/main/charts/nextcloud
---
nextcloud:
  host: "cloud.kellehorreur.de"
  trustedDomains:
    - "cloud.kellehorreur.de"
  existingSecret:
    enabled: true
    secretName: nextcloud-admin
    passwordKey: admin_pw
    usernameKey: admin_user
    tokenKey: null
    smtpUsernameKey: null # TODO
    smtpPasswordKey: null # TODO
    smtpHostKey: null # TODO

phpClientHttpsFix:
  enabled: true
  protocol: https

persistence:
  enabled: true
  size: 8Gi
  nextcloudData:
    enabled: true
    storageClass: smb-csi
    accessModes:
      - ReadWriteOnce
    size: 100Gi

cronjob:
  enabled: true

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 80

internalDatabase:
  enabled: false

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        existingSecret: nextcloud-database-pws
        secretKeys:
          adminPasswordKey: admin_pw
          userPasswordKey: user_pw
          replicationPasswordKey: replication_pw
  primary:
    persistence:
      enabled: true
    resources:
      limits:
        cpu: 350m # was 150m
        memory: 192Mi
        ephemeral-storage: 2Gi
      requests:
        cpu: 150m
        memory: 128Mi
        ephemeral-storage: 50Mi

externalDatabase:
  enabled: true
  type: postgresql
  host: "nextcloud-postgresql:5432"
  existingSecret:
    enabled: true
    secretName: nextcloud-database-pws
    passwordKey: user_pw
    usernameKey: user_name

redis:
  enabled: true

nginx:
  enabled: true
  config:
    default: true
    headers:
      # -- HSTS settings
      # WARNING: Only add the preload option once you read about
      # the consequences in https://hstspreload.org/. This option
      # will add the domain to a hardcoded list that is shipped
      # in all major browsers and getting removed from this list
      # could take several months.
      # Example:
      "Strict-Transport-Security": "max-age=15768000; includeSubDomains; preload;"
      "Referrer-Policy": "no-referrer"
      "X-Content-Type-Options": "nosniff"
      "X-Frame-Options": "SAMEORIGIN"
      "X-Permitted-Cross-Domain-Policies": "none"
      "X-Robots-Tag": "noindex, nofollow"
      "X-XSS-Protection": "1; mode=block"

image:
  repository: kellehorreur/nextcloud
  tag: 32.0.6-fpm
  pullPolicy: IfNotPresent
