# https://github.com/nextcloud/helm/tree/main/charts/nextcloud
---
nextcloud:
  host: "cloud.kellehorreur.de"
  trustedDomains:
    - "cloud.kellehorreur.de"
  existingSecret:
    enabled: true
    secretName: nextcloud-admin
    passwordKey: admin_pw
    usernameKey: admin_user
    tokenKey: null
    smtpUsernameKey: null # TODO
    smtpPasswordKey: null # TODO
    smtpHostKey: null # TODO

phpClientHttpsFix:
  enabled: true
  protocol: https

persistence:
  enabled: true
  size: 8Gi
  nextcloudData:
    enabled: true
    storageClass: smb-csi
    accessModes:
      - ReadWriteOnce
    size: 100Gi

cronjob:
  enabled: true

ingress:
  enabled: false

service:
  type: ClusterIP
  port: 80

internalDatabase:
  enabled: false

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        existingSecret: nextcloud-database-pws
        secretKeys:
          adminPasswordKey: admin_pw
          userPasswordKey: user_pw
          replicationPasswordKey: replication_pw
  primary:
    persistence:
      enabled: true

externalDatabase:
  enabled: true
  type: postgresql
  host: "nextcloud-postgresql:5432"
  existingSecret:
    enabled: true
    secretName: nextcloud-database-pws
    passwordKey: user_pw
    usernameKey: user_name

# TODO smb support
# image: needed for php-smbclient support https://github.com/nextcloud/helm/issues/205#issuecomment-2252118329
# Was used by default:      docker.io/library/nextcloud:32.0.3-apache
