---
- name: Streaming Server (IPv4 to IPv6)
  vars:
      ha_port: 8123
  hosts: ionos1
  roles:
      - role: firewall
        vars:
            firewall_allow_ipv6_ssh: true
            firewall_allow_http: ipv4
            firewall_allow_https: ipv4
            firewall_allow_ha: ipv4
            firewall_ha_port: "{{ ha_port }}"
      - role: nginx_stream
        vars:
            nginx_stream_ha_stream_enabled: true
            nginx_stream_ha_https_enabled: true
            nginx_stream_cloud_https_enabled: true
            nginx_stream_default_https_enabled: true
            nginx_stream_certs_path: "/etc/ionoshttps/kellehorreur.de/"
            nginx_stream_default_server_name: "*.kellehorreur.de"
            nginx_stream_cloud_domain: "cloud.kellehorreur.de"
            nginx_stream_ha_domain: "ha.kellehorreur.de"
            nginx_stream_ha_port: "{{ ha_port }}"
