---
- name: Streaming Server (IPv4 to IPv6)
  hosts: ionos1
  roles:
      - firewall_stream
      - role: nginx_stream
        vars:
            nginx_stream_ha_stream_enabled: true
            nginx_stream_ha_https_enabled: true
            nginx_stream_cloud_https_enabled: true
            nginx_stream_default_https_enabled: true
