---
- name: Create ssl secret in flux cluster
  hosts: piserver
  gather_facts: true
  become: true
  roles:
      - role: k8s_tls
        vars:
            k8s_tls_namespace: flux-system
            k8s_tls_secret_name: tls-certificate

- name: Create pihole admin-pw secret in flux cluster
  hosts: piserver
  gather_facts: true
  become: true
  vars_files:
      - "{{ playbook_dir }}/../secrets/pihole.yml"
  roles:
      - role: k8s_secret
        vars:
            k8s_secret_namespace: pihole
            k8s_secret_secret_name: pihole-admin-pw
            k8s_secret_secret_contents:
                - key: password
                  value: "{{ admin_pw }}"

- name: Create nextcloud database/postgres secret in flux cluster
  hosts: piserver
  gather_facts: true
  become: true
  vars_files:
      - "{{ playbook_dir }}/../secrets/nextcloud.yml"
  roles:
      - role: k8s_secret
        vars:
            k8s_secret_namespace: nextcloud
            k8s_secret_secret_name: nextcloud-database-pws
            k8s_secret_secret_contents:
                - key: admin_pw
                  value: "{{ postgres_admin_pw }}"
                - key: user_pw
                  value: "{{ postgres_user_pw }}"
                - key: replication_pw
                  value: "{{ postgres_replication_pw }}"
                - key: user_name
                  value: "nextcloud"

- name: Create nextcloud admin secret in flux cluster
  hosts: piserver
  gather_facts: true
  become: true
  vars_files:
      - "{{ playbook_dir }}/../secrets/nextcloud.yml"
  roles:
      - role: k8s_secret
        vars:
            k8s_secret_namespace: nextcloud
            k8s_secret_secret_name: nextcloud-admin
            k8s_secret_secret_contents:
                - key: admin_pw
                  value: "{{ nextcloud_admin_pw }}"
                - key: admin_user
                  value: "jonasadmin"

- name: Create smb credentials secret in flux cluster
  hosts: piserver
  gather_facts: true
  become: true
  vars_files:
      - "{{ playbook_dir }}/../secrets/smb.yml"
  roles:
      - role: k8s_secret
        vars:
            k8s_secret_namespace: smbstorage
            k8s_secret_secret_name: smbcredentials
            k8s_secret_secret_contents:
                - key: username
                  value: "{{ smb_username }}"
                - key: password
                  value: "{{ smb_password }}"
