# Installs a local system to my preferences
---
- name: Local Installation
  hosts: localhost
  become: true

  pre_tasks:
      - name: Update apt cache and upgrade packages
        ansible.builtin.package:
            update_cache: true
            cache_valid_time: 1800
            upgrade: "yes"

  roles:
      - role: dotfiles
        vars:
            dotfiles_profile_name: "jonas"
            dotfiles_set_bashrc: false
# ---

# TODO: gnome and gnome-tweaks https://gist.github.com/jonas-kell/44ecd5f06583ff119814f7d3dd06babc
# then conversion to wayland/sway
