---
- name: Pi Server (Mainly Kubernetes)
  hosts: piserver
  roles:
      - role: firewall
        vars:
            firewall_allow_ipv6_ssh: false
            firewall_allow_http: both
            firewall_allow_https: both
            firewall_allow_dns: ipv4
            firewall_allow_k3s: ipv4 # will get partially overwritten by k3s install (but NOT the ipv6 block on the apiserver)
      - role: nginx_stream
        vars:
            nginx_stream_into_k3s:
                - port_from: 80
                  port_to: 30080
                  target_ip: "{{ primary_ip }}"
                  tcp: true
                  udp: false
                - port_from: 443
                  port_to: 30443
                  target_ip: "{{ primary_ip }}"
                  tcp: true
                  udp: false
  become: true

- name: "K3s installation: Main node on Pi"
  ansible.builtin.import_playbook: "./k3s_install.yml"

- name: "K3s flux installation"
  ansible.builtin.import_playbook: "./k3s_flux_install.yml"

- name: Create ssl secret in flux cluster
  hosts: piserver
  gather_facts: true
  become: true
  roles:
      - role: k8s_tls
        vars:
            k8s_tls_namespace: flux-system
            k8s_tls_secret_name: tls-certificate

- name: Create admin-pw secret in flux cluster
  hosts: piserver
  gather_facts: true
  become: true
  vars_files:
      - "{{ playbook_dir }}/../secrets/pihole.yml"
  roles:
      - role: k8s_secret
        vars:
            k8s_secret_namespace: pihole
            k8s_secret_secret_name: pihole-admin-pw
            k8s_secret_secret_contents:
                - key: password
                  value: "{{ admin_pw }}"
