---
- name: Pi Server (Mainly Kubernetes)
  hosts: piserver
  roles:
      - role: firewall
        vars:
            firewall_allow_ipv6_ssh: false
            firewall_allow_http: none
            firewall_allow_https: none
            firewall_allow_dns: none
            firewall_allow_k3s: ipv4
  become: true
