---
- name: Using ubiquiti.unifi_api.network with this API
  hosts: localhost
  gather_facts: false
  vars:
      # Replace with your console IP (LAN)
      console_ip: "192.168.2.1"
      token: "{{ lookup('vars', 'ubiquiti_api_token') }}"
  vars_files:
      - "{{ playbook_dir }}/../secrets/ubiquiti_api_token.yml"
  roles:
      - role: unifi_firewall_writing
        vars:
            unifi_firewall_writing_unifi_token: "{{ token }}"
            unifi_firewall_writing_console_ip: "{{ console_ip }}"
