---
- name: Using ubiquiti.unifi_api.network with this API
  hosts: localhost
  gather_facts: false
  vars:
      # Replace with your console IP (LAN)
      console_ip: "192.168.2.1"
      token: "{{ lookup('vars', 'ubiquiti_api_token') }}"

      # Print debug setting
      print_debug: false
  vars_files:
      - "{{ playbook_dir }}/../secrets/ubiquiti_api_token.yml"
      - "{{ playbook_dir }}/../secrets/ionos_dns_api.yml"

  tasks:
      - name: Gather ip of the Homeassistant instance from DNS
        ansible.builtin.set_fact:
            haserver_ipv6: "{{ lookup('ansible.builtin.dig', 'ha.kellehorreur.de', 'qtype=AAAA', wantlist=True) | first }}"

      - name: Debug-print the ipv6 of the Homeassistant instance
        when: print_debug
        ansible.builtin.debug:
            var: haserver_ipv6

      - name: Gather facts from remote host
        ansible.builtin.setup:
        delegate_to: piserver
        delegate_facts: true
        register: piserver_gathered_data

      - name: Debug-print the gathered facts about the piserver
        when: print_debug
        ansible.builtin.debug:
            var: piserver_gathered_data

      - name: Extract the IPV6 address
        ansible.builtin.set_fact:
            piserver_ipv6: >-
                {{ piserver_gathered_data.ansible_facts.ansible_all_ipv6_addresses
                | ansible.utils.ipv6('2000::/3')
                | list
                | first }}

      - name: Debug-print the gathered IPV6 address
        when: print_debug
        ansible.builtin.debug:
            var: piserver_ipv6

      - name: Run write to unifi role
        ansible.builtin.include_role:
            name: unifi_firewall_writing
        vars:
            unifi_firewall_writing_unifi_token: "{{ token }}"
            unifi_firewall_writing_console_ip: "{{ console_ip }}"
            unifi_firewall_writing_print_debug: "{{ print_debug }}"
            unifi_firewall_writing_replacement_dict:
                - name: "Cloud Server PI"
                  replacement_ip: "{{ piserver_ipv6 }}"
                - name: "Home Assistant PI"
                  replacement_ip: "{{ haserver_ipv6 }}"

      - name: Write the DNS settings to Ionos DNS
        custom.dns.ionosdns:
            prefix: "{{ ionos_api_prefix }}"
            key: "{{ ionos_api_key }}"
            zone_domain: "kellehorreur.de"
            domain: "cloud.kellehorreur.de"
            target_ipv6_address: "{{ piserver_ipv6 }}"
            log_http_traffic: true
        register: ionosapi_results

      - name: Debug-print the output of the Ionos DNS API call
        when: print_debug
        ansible.builtin.debug:
            var: ionosapi_results
# ---

# Lists can be found at: https://unifi.ui.com/ > Network > Settings > Overview > Network Lists
# They can be used at: https://unifi.ui.com/ > Network > Settings > Policy Engine
